# 이름이 있는 동물의 아이디디
# 1.
SELECT ANIMAL_ID FROM ANIMAL_INS WHERE NAME IS NOT NULL;
# 2.
SELECT ANIMAL_ID FROM ANIMAL_INS WHERE NAME IS NOT NULL ORDER BY ANIMAL_ID;
# 3.
SELECT ANIMAL_ID FROM ANIMAL_INS WHERE NAME IS NOT NULL ORDER BY ANIMAL_ID ASC;

# 이름이 없는 동물의 아이디는 WHERE절에서 IS NOT NULL 을 IS NULL로 변경.